### PR TITLE
Implemented DB2IBMiConnection

### PR DESCRIPTION
**Pull request by cassvail**
Implemented DB2IBMiConnection with accessible _conn resource to allow IBMi XMLToolkit usage on current Driver Connection

### CODE REVIEW

**Comment by asgrim** [comment]
Hmm, I see what you're trying to do here, but I don't think it makes any sense to add this here as it means duplicating the entire `DB2Connection` class which I think should be avoided. I think a better option would be to suggest putting a PR into https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/IBMDB2/DB2Connection.php to add the method directly to access the `_conn` resource handle.

**Comment by cassvail** [comment]
@asgrim I perfectly agree with you! I already put a PR, but sadly the doctrine team doesn't seem to be very collaborative on this subject. https://github.com/doctrine/dbal/pull/2424

**Comment by cassvail** [comment]
Hi @asgrim, any news on merging this pull request? 
If I want to switch to this repo in my production projects this edit is necessary or the IBMi XMLToolkit won't work correctly, i.e. when changing library list inside the connection

**Comment by asgrim** [comment]
Hmm, I think the same logic from Marco applies here regarding accessing that connection handle. I'd suggest either using regular reflection if you need to access the connection handle, or you could use Better Reflection to add a method to the `doctrine/dbal`'s DB2Connection class (note: don't do this at runtime). Bear in mind, the connection handle is hidden for BC reasons, and that makes sense IMO here too.

Reflection should be fine, e.g. :

```php
$connProperty = new \ReflectionProperty(Doctrine\DBAL\Driver\IBMDB2\DB2Connection::class, '_conn');
$connProperty->setAccessible(true);
$conn = $connProperty->getValue($connectionInstance);
```

**Comment by asgrim** [comment]
Or of course, extend the `DoctrineDbalIbmi\Driver\DB2IBMiConnection` within the application context where you're using it, that also works

**Comment by asgrim** [comment]
@cassvail that's fine & preferable - could you squash into one commit though please? :)

**Comment by cassvail** [comment]
@asgrim Of course! Reflection was a brilliant idea, thanks for the advice.

**Comment by asgrim** [comment]
Thanks @cassvail :)

**Pull request merged**
